# Specify version format
version: "{build}"

os:
  - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\Toon

before_build:
  - ps: . C:\projects\Toon\Scripts\ci-install-vulkan.ps1
  - ps: cmake --version
  - ps: Get-ChildItem "env:"

build_script:
  - cmd: cd C:\projects\Toon
  - cmd: mkdir Build
  - cmd: cd Build
  # TODO -DBUILD_TESTS=ON
  - cmd: cmake -G "Visual Studio 16 2019" -A x64 ..
  - cmd: cmake --build .
  # - cmd: cmake --build . --target RUN_TESTS

test: off
