#ifndef TEMPORALITY_STBI_CONFIG_HPP
#define TEMPORALITY_STBI_CONFIG_HPP

#include <Temporality/Config.hpp>

#if defined(TEMPORALITY_STBI_EXPORT)
    #define TEMPORALITY_STBI_API TEMPORALITY_API_EXPORT
#else
    #define TEMPORALITY_STBI_API TEMPORALITY_API_IMPORT
#endif

#include <Temporality/Macros.hpp>

#endif // TEMPORALITY_STBI_CONFIG_HPP